### PR TITLE
Question papers added

### PR DESCRIPTION
**Pull request by azimwarsii**
Hey I've added a link to the readme file which directs to a repository containing all previous question papers for the 3rd Semester. 
Screenshot 2022-11-20 220208

### CODE REVIEW

**Comment by saha-indranil** [comment]
Please remove the line number 65 in the readme file. I'll merge after that

**Comment by AzimWarsii** [comment]
Oh my bad that was by mistake

**Comment by AzimWarsii** [comment]
Done

**Comment by AzimWarsii** [comment]
Thanks man

**Pull request merged**
